---
sudo: false
language: c
matrix:
  include:
    - env: TEST=repos-lint
      language: python
      python: '3.6'
      install: pip install -r requirements.txt
      script: ./bin/repos-lint ./etc/repos.yaml

    - env: TEST=yamllint
      language: c
      services:
        - docker
      script: ./tests/yamllint.sh

    - env: TEST=shellcheck
      language: c
      services:
        - docker
      script: ./tests/shellcheck.sh

    - env: TEST=markdownlint
      language: c
      services:
        - docker
      script: ./tests/mdl.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
